# Generated by Django 4.0.10 on 2024-03-11 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
