# Generated by Django 4.0.10 on 2024-03-11 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0002_alter_hit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='referer',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.URLField(max_length=1000, unique=True),
        ),
    ]
