# Generated by Django 4.0.10 on 2024-02-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hit',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='Hit',
        ),
    ]
