# Generated by Django 4.0.10 on 2024-02-12 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0007_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.CharField(max_length=50),
        ),
    ]
