# Generated by Django 4.0.10 on 2024-02-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0008_alter_client_client_ip_alter_page_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
