# Generated by Django 4.0.10 on 2024-02-12 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0011_alter_page_page_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ip',
            field=models.GenericIPAddressField(),
        ),
    ]
