# Generated by Django 4.0.10 on 2024-02-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0015_alter_client_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.URLField(unique=True),
        ),
    ]
