# Generated by Django 4.0.10 on 2024-02-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0009_alter_client_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name='hit',
            name='referer',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='hit',
            name='timestamp',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='page',
            name='page_url',
            field=models.URLField(unique=True),
        ),
    ]
