# Generated by Django 4.0.10 on 2024-02-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0012_alter_client_client_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hit',
            name='timestamp',
            field=models.TimeField(),
        ),
    ]
