# Generated by Django 4.0.10 on 2024-02-16 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monappli', '0014_alter_hit_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='client_ip',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
